### ISSUE TITLE
admin play next function

### ISSUE THREAD

**Issue by FelixGail** [BjoernPetersen/AndroidMusicBot#37]
Just as the enqueue again function for already played songs, a song in the queue could be moved to the top of the queue by an admin by pressing on it.

**Comment by BjoernPetersen** [comment]
I don't really see why this is needed. The admin can just drag the song to the top

**Comment by FelixGail** [comment]
yes, but using the bot yesterday showed that most of the time one would want to move a song to the top instead of around, that the playlist can get quite long and that most of the time the last song in the playlist is the song wanted at the top. Together this makes the whole process quite laborious. Plus clicking on the song is currently not coupled with any action

**Comment by BjoernPetersen** [comment]
I agree
